[tool.poetry]
name = "opentutor-classifier"
version = "1.0.0"
description = "train and run inference for open tutor"
authors = []

[tool.poetry.dependencies]
# python = "^3.8"
python = ">=3.8,<3.10"
celery = "==5.0.5"
Cerberus = "==1.3.4"
Flask = "==2.0.0"
Flask-Cors = "==3.0.10"
gunicorn = "==20.1.0"
python-dotenv = ">=0.17.1"
redis = "==3.5.3"
Werkzeug = "==2.0.1"
gensim = "4.0.1"
click = "<8"
pandas = "==1.2.4"
PyYAML = "==5.4.1"
pylru = "==1.2.0"
nltk = "==3.6.2"
numpy = "==1.21.0"
requests = "==2.25.1"
scikit-learn = "==0.24.2"
text2num = "==2.2.1"
scipy = "==1.6.3"

[tool.poetry.dev-dependencies]
coverage = "==5.5"
freezegun = "==1.1.0"
pip-upgrader = "^1.4.15"
pytest = "==6.2.4"
pytest-env = "==0.6.2"
pytest-only = "==1.2.2"
pytest-mock = "==3.6.1"
responses = "==0.13.3"
tqdm = "==4.60.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
