FROM public.ecr.aws/lambda/python:3.8

WORKDIR /app

ENV PYTHONPATH /app
ENV PATH="/app/bin:${PATH}"
RUN yum install gcc -y
COPY requirements-extract_config.txt ./requirements.txt
# RUN python -m pip install --upgrade pip
RUN pip install --no-cache -r requirements.txt
COPY functions/extract_config.py ./
COPY src src
COPY opentutor_classifier opentutor_classifier
