name: classifier - build/pub release
on:
  push:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Run format test
        run: cd opentutor_classifier && make test-format
      - name: Run lint test
        run: cd opentutor_classifier && make test-lint
      - name: Run types test
        run: cd opentutor_classifier && make test-types
      - name: Run license test
        run: cd opentutor_classifier && make test-license
      - name: Run tests
        run: cd opentutor_classifier && make test

  build-and-publish:
    needs: test
    name: Push docker image to docker hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker tag
        id: tag
        run: |
          IMAGE_TAG=${GITHUB_SHA::8}
          echo ::set-output name=image_tag::${IMAGE_TAG}
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_LOGIN }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker build
        run: cd opentutor_classifier && docker build -t uscictdocker/opentutor-classifier:${{ steps.tag.outputs.image_tag }} .
      - name: Docker tag
        if: startsWith(github.ref, 'refs/tags/')
        run: docker tag "uscictdocker/opentutor-classifier:${{ steps.tag.outputs.image_tag }}" "uscictdocker/opentutor-classifier:${GITHUB_REF#refs/tags/}"
      - name: Docker push
        run: docker push uscictdocker/opentutor-classifier
